apiVersion: v1
kind: Pod
metadata:
  name: baspod
spec:
  initContainers:
  - name: initcontainer01
    image: docker.io/istio/proxyv2
  containers:
  - name: container01
    image: dummyimagename
    securityContext:
      runAsNonRoot: true
